Repository opt-nc/geol, pull requests merged in 2025-10, with the labels that each got.

#93 doc: Better cli description
  .goreleaser.yaml
  cmd/root.go
Labels: BUILD, documentation, enhancement, quickfix

#94 :memo: Add an example for the "n" option to the extended sub-command
  cmd/product/extended.go
Labels: BUILD, documentation, enhancement, quickfix, persona:sysadmin, persona:devops, persona:auditor, productivity

#95 doc: SECURITY.md
  SECURITY.md
Labels: BUILD, quickfix, communication, security

#100 Supervinh patch
  .github/config.yml
  cmd/cache/local/status.go
  cmd/list/items/categories.go
  cmd/list/items/products.go
  cmd/list/items/tags.go
  cmd/list/list.go
  cmd/product/describe.go
  cmd/product/extended.go
  cmd/product/product.go
  cmd/root.go
  utilities/tools.go
Labels: RUN, bug, enhancement

#101 Develop
  .github/config.yml
  .github/workflows/IssuesCloseStale.yml
  .goreleaser.yaml
  README.md
  SECURITY.md
  assets/logo-no-name.svg
  assets/logo-with-name.svg
  cmd/cache/local/status.go
  cmd/list/items/categories.go
  cmd/list/items/products.go
  cmd/list/items/tags.go
  cmd/list/list.go
  cmd/product/describe.go
  cmd/product/extended.go
  cmd/product/product.go
  cmd/root.go
  utilities/tools.go
Labels: RUN, bug, enhancement
