Repository opt-nc/geol, pull requests merged in 2025-09, with the labels that each got.

#50 First release
  .github/dependabot.yml
  .github/workflows/IssuesCloseStale.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/test-release.yml
  .gitignore
  .goreleaser.yaml
  .releaserc.json
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  Taskfile.yml
  cmd/about.go
  cmd/cache/cache.go
  cmd/cache/local/clear.go
  cmd/cache/local/refresh.go
  cmd/cache/local/status.go
  cmd/list.go
  cmd/product/describe.go
  cmd/product/extended.go
  cmd/product/product.go
  cmd/root.go
  cmd/version.go
  completions/geol.bash
  completions/geol.fish
  completions/geol.zsh
  go.mod
  go.sum
  main.go
  personas/01-ken-sys-admin.md
  personas/02-grace-ciso.md
  personas/03-patrick-devops.md
  personas/04-ada-developer.md
  personas/05-gordon-cio.md
  personas/06-edsger-auditor.md
  personas/07-richard-contributor.md
  personas/README.md
  utilities/tools.go
Labels: BUILD, documentation, enhancement

#59 Develop
  .github/workflows/IssuesCloseStale.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/test-release.yml
  .goreleaser.yaml
  go.mod
  go.sum
Labels: BUILD, quickfix, dependencies

#60 fix: add completion files
  .goreleaser.yaml
Labels: BUILD, quickfix

#63 fix: add scripts
  .goreleaser.yaml
  scripts/manpages.sh
Labels: BUILD, quickfix

#65 Develop
  .goreleaser.yaml
  completions/geol.bash
  completions/geol.fish
  completions/geol.zsh
  scripts/completions.sh
  scripts/manpages.sh
Labels: BUILD, quickfix

#66 Update
  README.md
  go.mod
  go.sum
Labels: BUILD, quickfix, dependencies

#72 🏆 Integrate "OpenSSF Best Practices Badge Program" 🏷️
  README.md
Labels: BUILD, documentation, quickfix, communication, persona:developer, persona:contributor

#75 Fixes
  cmd/about.go
  cmd/list.go
  cmd/product/describe.go
Labels: RUN, quickfix

#76 Update completion doc
  README.md
Labels: BUILD, documentation, quickfix

#80 :bug: doc: Create bug issue template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: BUILD, enhancement, quickfix, persona:developer
